# Frozen emissions configuration file
#
# This file specifies that only combustion sectors from the USA ISO are to be frozen
#
# Matt Nicholson
# 11 Feb 2020
#
# Members
# --------
# freeze:
#   year    : Freeze emission factors for years >= freeze_year.
#   isos    : ISOs to freeze.
#   species : Emission species to freeze
# ceds:
#   year_first : First year of CEDS output. Default is 1750
#   year_last  : Last year of CEDS output. Default is 2015
#
# Change log
# ----------
# 9 April 2020
#   * Remove 'dirs' key & all sub-keys & values.
---
freeze:
  year: 1970
  isos: [usa]
  species: [BC, CH4, CO, CO2, NH3, NMVOC, NOx, OC, SO2]
ceds:
  year_first: 1750
  year_last: 2014