# A basic configuration YAML file
#
# Matt Nicholson
# 12 Feb 2020
#
# Members
# --------
# dirs:
#   cmip6_inter : Path to the CMIP6 emissions 'intermediate-output' directory.
#   root_inter  : Path of the root intermediate output directory.
#   rot_proj    : Root project directory
#   input       : Project input directory
#   output      : Project output directory
#   logs        : Project log directory
#   init        : Project initialization/configuration directory
# freeze:
#   year    : Freeze emission factors for years >= freeze_year.
#   isos    : ISOs to freeze.
#   species : Emission species to freeze
# ceds:
#   year_first : First year of CEDS output. Default is 1750
#   year_last  : Last year of CEDS output. Default is 2015
---
dirs:
  win:
    cmip6: C:\Users\nich980\data\e-freeze\CMIP6-emissions\intermediate-output
    ceds: C:\Users\nich980\code\CEDS-dev
  linux: 
    cmip6: /mnt/c/Users/nich980/data/e-freeze/CMIP6-emissions/intermediate-output
    ceds: /mnt/c/Users/nich980/code/CEDS-dev
freeze:
  year: 1970
  isos: all
  species: [BC, CH4, CO, CO2, NH3, NMVOC, NOx, OC, SO2]
ceds:
  year_first: 1750
  year_last: 2014