name: frozen-emissions
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cycler=0.10.0
  - freetype=2.10.0
  - icc_rt=2019.0.0
  - icu=64.2
  - intel-openmp=2020.0
  - jpeg=9c
  - kiwisolver=1.1.0
  - libclang=9.0.1
  - libpng=1.6.37
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - pandas=1.0.1
  - pip=20.0.2
  - pyparsing=2.4.6
  - pyqt=5.12.3
  - python=3.6.7
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyyaml=5.3
  - qt=5.12.5
  - scipy=1.4.1
  - setuptools=45.2.0
  - six=1.14.0
  - sqlite=3.30.1
  - tornado=6.0.3
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.34.2
  - wincertstore=0.2
  - yaml=0.2.2
  - zlib=1.2.11
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1

